---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit-frontend
  name: streamlit-app
  namespace: fastapi-backend

spec:
  selector:
    matchLabels:
      app: streamlit-app
  replicas: 1
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-frontend-service-container
          imagePullPolicy: IfNotPresent
          image: rvarma123/streamlit-app
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
          ports:
          - containerPort: 8502
      imagePullSecrets:
        - name: registry-credentials