---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit-frontend
  name: streamlit-app
  namespace: fastapi-backend

spec:
  selector:
    matchLabels:
      app: streamlit-app
  replicas: 1
  template:
    metadata:
      labels:
        app: streamlit-app
    
    containers:
      - name: streamlit-frontend-service
        imagePullPolicy: IfNotPresent4
        image: rvarma123/ml-services-frontend
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
        ports:
          containerPort: 8502
    imagePullSecrets:
      - name: registry-credentials