---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamlit-app-svc
  name: streamlit-app-svc
  namespace: fastapi-backend
spec:
  type: ClusterIP
  selector:
    app: streamlit-app
  ports:
  - name: streamlit
    port: 8502
    targetPort: 8502
