apiVersion: v1
kind: Service
metadata:
  labels:
    app: text-summarization-svc
  name: text-summarization-svc
  namespace: fastapi-backend
spec:
  type: ClusterIP
  selector:
    app: text-summarization
  ports:
  - name: summarize
    port: 81
    targetPort: 81
