---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: visual-question-answering-svc
  name: visual-question-answering-svc
  namespace: fastapi-backend

spec:
  type: ClusterIP
  selector:
    app: visual-question-answering
  ports:
  - name: compute
    port: 80
    targetPort: 80
